### ISSUE TITLE
Cython and datatype error

### ISSUE THREAD

**Issue by jrahimik** [ngoix/OCRF#11]
I am following your installation directions:

After running python setup.py install in python 2 environment I am getting this error:

Partial import of sklearn during the build process.
Generating cython files
Cythonizing sources
sklearn
sklearn/_isotonic.pyx has not changed
sklearn/__check_build/_check_build.pyx has not changed
sklearn/cluster/_dbscan_inner.pyx has not changed
Processing sklearn/cluster/_hierarchical.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from libcpp.map cimport map as cpp_map

# Import the C-level symbols of numpy
cimport numpy as np

DTYPE = np.float64
         ^
------------------------------------------------------------

sklearn/utils/fast_dict.pxd:13:10: cimported module has no attribute 'float64'
Traceback (most recent call last):
  File "/home/javad/OCRF/build_tools/cythonize.py", line 198, in <module>
    main(root_dir_arg)
  File "/home/javad/OCRF/build_tools/cythonize.py", line 190, in main
    check_and_cythonize(root_dir)
  File "/home/javad/OCRF/build_tools/cythonize.py", line 182, in check_and_cythonize
    cythonize_if_unchanged(cur_dir, cython_file, gen_file, hashes)
  File "/home/javad/OCRF/build_tools/cythonize.py", line 156, in cythonize_if_unchanged
    cythonize(full_cython_path, full_gen_file_path)
  File "/home/javad/OCRF/build_tools/cythonize.py", line 75, in cythonize
    raise Exception('Cythonizing %s failed' % cython_file)
Exception: Cythonizing sklearn/cluster/_hierarchical.pyx failed
Traceback (most recent call last):
  File "setup.py", line 315, in <module>
    setup_package()
  File "setup.py", line 299, in setup_package
    generate_cython()
  File "setup.py", line 185, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!
(py27) [javad@br005 OCRF]$

**Comment by zakariazouaoui** [comment]
i have the same error and i can't find a solution, did you find a way to overcome this error
